### ISSUE TITLE
在获取profile时有问题

### ISSUE THREAD

**Issue by captain100** [wenwei1202/passport-wechat-enterprise#1]
WechatEnterpriseStrategy.prototype.getUserInfo = function(code,accessToken) {
  var self = this;
  function verified(err, user, info) {
    if (err) {
      return self.error(err);
    }
    if (!user) {
      return self.fail(info);
    }
    self.success(user, info);
  }

  function verifyResult(accessToken, refreshToken, params,profile,verified) {
    try {
      if (self._passReqToCallback) {
        var arity = self._verify.length;
        if (arity == 6) {
          self._verify(req, accessToken, refreshToken, params, profile, verified);
        } else { // arity == 5
          self._verify(req, accessToken, refreshToken, profile, verified);
        }
      } else {
        var arity = self._verify.length;
        if (arity == 5) {
          self._verify(accessToken, refreshToken, params, profile, verified);
        } else { // arity == 4
          self._verify(accessToken, refreshToken, profile, verified);
        }
      }
    } catch (ex) {
           return self.error(ex);
    }
  }

  this._oauth2.getUserInfo(accessToken, code, function(err, profile){
    if(err) {
      return self.error(err);
    }
    profile.id = profile.UserId;
    if(profile.UserId) {
      verifyResult(null, null,null, profile, verified);
    } else {
      self.fail();
    }

  });
};
 总抛出异常无法得到profile

并且在saveaccesstoken   时this._saveaccessToken()有误

**Comment by vcwen** [comment]
可以下你具体使用的代码，看下你是如何传入getAccessToken和saveAccessToken，可能是没有获取到正确的accesstoken

**Comment by captain100** [comment]
passport.use("wechat-enterprise", new WechatPublicStrategy({
        corpId: 'wx306a8629aca93739',
        corpSecret: 'iIChKj2NbXS74RlDHpr2_9f3r6VUIKbYueydJhQj58BqfUMuPnPvodEzbx0tUTq6',
        callbackURL: "http://sz.xiaoyun.com:3000/auth/auth/wechat/callback",
        state: "STATE",
        scope: "snsapi_userinfo"
    },
    function (profile, done) {
        console.log('profile =  ' + profile);
        //存储用户信息
        done(null,profile.UserId);
    },
    function getAccessToken(cb) {
        return cb();
    },
    function saveAccessToken(accessToken, cb) {
        console.log(accessToken);
        return cb;
    }
));

router.get('/auth/wechat', passport.authenticate('wechat-enterprise'));

router.get('/auth/wechat/callback', passport.authenticate('wechat-enterprise', {failureRedirect: '/login'}),function(req,res){
    console.log(req);
    res.redirect('http://sz.xiaoyun.com:3000/list');
});
我看能获得accesstoken并且我跑断点也获得了userId就是不发回调

------------------ 原始邮件 ------------------
发件人: "Vincent Wen";notifications@github.com;
发送时间: 2015年11月10日(星期二) 上午10:59
收件人: "wenwei1202/passport-wechat-enterprise"passport-wechat-enterprise@noreply.github.com; 
抄送: "雪域金翅"870736375@qq.com; 
主题: Re: [passport-wechat-enterprise] 在获取profile时有问题 (#1)

可以下你具体使用的代码，看下你是如何传入getAccessToken和saveAccessToken，可能是没有获取到正确的accesstoken

**Comment by vcwen** [comment]
scope在企业号中现在只支持snsapi_base

**Comment by captain100** [comment]
啊 只不是问题的关键我只是试了一下snsapi_userinfo的效果

------------------ 原始邮件 ------------------
发件人: "Vincent Wen";notifications@github.com;
发送时间: 2015年11月10日(星期二) 中午11:08
收件人: "wenwei1202/passport-wechat-enterprise"passport-wechat-enterprise@noreply.github.com; 
抄送: "雪域金翅"870736375@qq.com; 
主题: Re: [passport-wechat-enterprise] 在获取profile时有问题 (#1)

scope在企业号中现在只支持snsapi_base

**Comment by captain100** [comment]
首先遇到的问题是 this._saveaccessToken()没定义 在oauth.js的47行
OAuth.prototype.getOAuthAccessToken= function(params, callback) {
  var self = this;
  var params= params || {};
  params['corpid'] = this._corpId;
  params['corpsecret'] = this._corpSecret;
  var url = AccessTokenUrl + "?" + querystring.stringify(params);
  request(url, function(err, res, body){
    if(err) return callback(err);
    var result = null;
    try {
      result = JSON.parse(body);
    } catch(e) {
      return callback(e);
    }
    if(result.errcode) return callback(result);
    var accessToken = new AccessToken(result.access_token, moment().add(7100, 'seconds').toDate());
    self._saveAccessToken(accessToken);
    callback(null, accessToken);
  });
}

**Comment by vcwen** [comment]
verify(accessToken, refreshToken, profile, verified) ，verify的方法至少有4个参数，因为你只有两个参数，所以出错了，为了兼容，所以至少4个，但是前面两个token都是null，你可以试试

**Comment by captain100** [comment]
还有在这个方法里 var arity = self._verify.length;是什么意思self._passReqToCallback也没定义
function verifyResult(accessToken, refreshToken, params,profile,verified) {
    try {
      if (self._passReqToCallback) {
        var arity = self._verify.length;
        if (arity == 6) {
          self._verify(req, accessToken, refreshToken, params, profile, verified);
        } else { // arity == 5
          self._verify(req, accessToken, refreshToken, profile, verified);
        }
      } else {
        var arity = self._verify.length;
        if (arity == 5) {
          self._verify(accessToken, refreshToken, params, profile, verified);
        } else { // arity == 4
          self._verify(accessToken, refreshToken, profile, verified);
        }
      }
    } catch (ex) {
      return self.error(ex);
    }
  }

**Comment by captain100** [comment]
我应该怎么修改？能详细说明一下吗

**Comment by captain100** [comment]
我把反回profile的function改成了四个参数就可以了，但
/weixin_demo/node_modules/passport-wechat-enterprise/lib/oauth.js:47
    this._saveAccessToken(accessToken);
         ^
TypeError: undefined is not a function

的代码错误需要修改
谢谢你写的代码很有用，希望能加你好友认识一下

------------------ 原始邮件 ------------------
发件人: "Vincent Wen";notifications@github.com;
发送时间: 2015年11月10日(星期二) 中午11:21
收件人: "wenwei1202/passport-wechat-enterprise"passport-wechat-enterprise@noreply.github.com; 
抄送: "雪域金翅"870736375@qq.com; 
主题: Re: [passport-wechat-enterprise] 在获取profile时有问题 (#1)

verify(accessToken, refreshToken, profile, verified) ，verify的方法至少有4个参数，因为你只有两个参数，所以出错了，为了兼容，所以至少4个，但是前面两个token都是null，你可以试试

**Comment by vcwen** [comment]
saveAccessToken，这个是个bug，稍等我我会修复下，更新之后我通知你，
_passReqToCallback是值钱故意没定义，觉得没什么用，怕以后忘记，所以把_passReqToCallback还是放那里，我一起加下

**Comment by vcwen** [comment]
已经修复了bug，版本更新了0.1.3，你可以更新下

**Comment by vcwen** [comment]
@captain100  现在auth已经解决了吗？

**Comment by captain100** [comment]
解决了谢谢

**Comment by vcwen** [comment]
不客气，那我关闭这个issue了
